name: 스토리북 S3 배포 ✌️

on:
    push:
        branches:
            - storybook/**

jobs:
    storybook:
        runs-on: ubuntu-latest
        outputs:
            status: ${{job.status}}
        permissions:
            id-token: write
            contents: read
        steps:
            - name: checkout repositoty
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: configure aws credentials ARN
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: install dependencies
              run: pnpm install

            - name: build storybook
              run: pnpm build-storybook

            - name: bucket sync
              run: |
                  aws s3 sync \
                  --region ap-northeast-2 \
                  ./storybook-static s3://anotherme-storybook \
                  --delete
